// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARBfuxtzSp9jQ5EZaLKoJegwgeFGgR8WQ',
    appId: '1:548422878639:web:9adb11c090366c799c1b5a',
    messagingSenderId: '548422878639',
    projectId: 'tapattend-59d1e',
    authDomain: 'tapattend-59d1e.firebaseapp.com',
    storageBucket: 'tapattend-59d1e.firebasestorage.app',
    measurementId: 'G-4PCQRNX76F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPcokehV9POWMbJwSaU_M0OZuk8qASH-o',
    appId: '1:548422878639:android:7ba5a94e87d13a0f9c1b5a',
    messagingSenderId: '548422878639',
    projectId: 'tapattend-59d1e',
    storageBucket: 'tapattend-59d1e.firebasestorage.app',
  );
}
